name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone external repository
        run: git clone https://github.com/sainiajay136/onlinebookshop.git

      - name: Upload cloned repo as artifact
        uses: actions/upload-artifact@v4
        with:
          name: onlinebookshop
          path: onlinebookshop

  build:
    needs: clone
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: onlinebookshop

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Run Maven Tests
        run: mvn test

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: onlinebookshop
          path: onlinebookshop

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: onlinebookshop
          path: onlinebookshop

      - name: Deploy WAR to Tomcat via curl
        env:
          TOMCAT_USERNAME: admin
          TOMCAT_PASSWORD: admin123
          TOMCAT_HOST: 192.168.85.228
          TOMCAT_PORT: 8085
           
        run: |
          curl -u admin:admin123 -T onlinebookshop "http://192.168.85.229:8085/manager/text/deploy?path=/yourapp&update=true"
